apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capstone-application
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      users=2407akshi/capstone_user:prod
      issues=2407akshi/capstone_issue:prod
      tickets=2407akshi/capstone_ticket:prod
      comments=2407akshi/capstone_comment:prod
      conversations=2407akshi/capstone_conversation:prod
      gateway=2407akshi/capstone_gateway:prod
    argocd-image-updater.argoproj.io/users.update-strategy: digest
    argocd-image-updater.argoproj.io/issues.update-strategy: digest
    argocd-image-updater.argoproj.io/tickets.update-strategy: digest
    argocd-image-updater.argoproj.io/comments.update-strategy: digest
    argocd-image-updater.argoproj.io/conversations.update-strategy: digest
    argocd-image-updater.argoproj.io/gateway.update-strategy: digest
spec:
  project: default
  source:
    repoURL: https://github.com/AkshithaRajavel/Capstone-deployment.git
    targetRevision: HEAD
    path: kube
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
