apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: 2407akshi/capstone_gateway
        ports:
        - containerPort: 8000
        env:
        - name: CAPSTONE_USERS_PORT
          value: "9090"
        - name: CAPSTONE_TICKETS_PORT
          value: "9092"
        - name: CAPSTONE_ISSUES_PORT
          value: "9093"
        - name: CAPSTONE_COMMENTS_PORT
          value: "9094"
        - name: CAPSTONE_CONVERSATIONS_PORT
          value: "9091"
        - name: CAPSTONE_COMMENTS_SERVICE 
          value: "comments-service"  
        - name: CAPSTONE_ISSUES_SERVICE
          value: "issues-service"
        - name: CAPSTONE_TICKETS_SERVICE
          value: "tickets-service"
        - name: CAPSTONE_USERS_SERVICE
          value: "conversations-service"
        - name: CAPSTONE_CONVERSATIONS_SERVICE
          value: "users-service"
        - name: JWTSECRET
          value: "DevDesk"

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30001
