apiVersion: apps/v1
kind: Deployment
metadata:
  name: issues-deployment
  labels:
    app: issues
spec:
  replicas: 1
  selector:
    matchLabels:
      app: issues
  template:
    metadata:
      labels:
        app: issues
    spec:
      containers:
      - name: issues
        image: 2407akshi/capstone_issue:prod
        ports:
        - containerPort: 9093
        env:
        - name: MONGO_URI
          value: "mongodb+srv://ilhansyed:devrevler@cluster0.daiu1xh.mongodb.net/?retryWrites=true&w=majority"
        - name: CAPSTONE_ISSUES_PORT
          value: "9093"
---
apiVersion: v1
kind: Service
metadata:
  name: issues-service
spec:
  selector:
    app: issues
  ports:
  - protocol: TCP
    port: 9093
    targetPort: 9093
