apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: 2407akshi/capstone_user:prod
        ports:
        - containerPort: 9090
        env:
        - name: MONGO_URI
          value: "mongodb+srv://ilhansyed:devrevler@cluster0.daiu1xh.mongodb.net/?retryWrites=true&w=majority"
        - name: CAPSTONE_USERS_PORT
          value: "9090"
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
